# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 박승연
title: 클라이언트 프로그래머
email: 2fastboii@gmail.com
# email_title: Email (Email title override)
phone: 010-8723-0648
# phone_title: Phone (Phone title override)
website: https://github.com/new6ie3 (eg. https://google.com)(optional)
# website_title: Github (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: jekyllrb
github_username:  jekyll
stackoverflow_username: "00000001"
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
xing_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
orcid_username: 0000-0000-0000-0000
googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: new6ie3
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://new6ie3.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: 소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: 포트폴리오
    layout: projects
    content:
      - layout: left
        border: weak
        title: Plunderer
        image: /images/projects/plunderer.png
        link: /projects/plunderer/
        tags:
          - Unity
          - C#
        quote: >
          실시간 전술 RPG 프로젝트
        description: |
          약한 주인공이 잠입과 탈취, 환경을 활용하여
          적과 싸우는 실시간 전술 RPG입니다.

      - layout: left
        border: weak
        title: Unity 2D Platformer
        link: /projects/platformer/
        link_text: 프로젝트 상세보기
        quote: >
          Unity 기반 2D 플랫폼 게임
        description: |
          Unity를 이용하여 제작한 2D 플랫폼 게임 프로젝트입니다.

      - layout: left
        border: weak
        title: DirectX Game
        link: /projects/directx-game/
        link_text: 프로젝트 상세보기
        quote: >
          C++ / DirectX 기반 게임 프로젝트입니다.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
          
  - title: 기타
    layout: etc
    content:

      - title: 자격증
        icon: "📜"
        items:
          - title: 정보처리기사
            sub_title: 한국산업인력공단

          - title: CosPro 2급
            sub_title: YBM

      - title: 논문
        icon: "📄"
        items:
          - title: 파이썬코드 도용방지를 위한 유사도 분석 도구 구현
            sub_title: 학술지 또는 학술대회명
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
